# Generated by Django 5.2.9 on 2026-08-31 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='make',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='model',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='odometer',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='transmission',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='year',
        ),
        migrations.AddField(
            model_name='listing',
            name='brand',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='dietary_preference',
            field=models.CharField(choices=[('none', 'None'), ('organic', 'Organic'), ('vegan', 'Vegan'), ('gluten_free', 'Gluten-Free')], default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='weight',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
